---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: bosh_exporter
      scrape_interval: 2m
      scrape_timeout: 1m

      static_configs:
      - targets:
        - 'bosh-exporter:9190'
